version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    network_mode: bridge
    image: localstack/localstack:0.14.2
    ports:
      - "127.0.0.1:53:53"                # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - SERVICES=apigatewayv2,apigateway,iam,lambda,cloudwatch,cloudfront
      - DEBUG=1
      #- DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      #- HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      #- DOCKER_HOST=unix:///var/run/docker.sock
      #- LAMBDA_DOCKER_NETWORK=localstack-tutorial
      - DOCKER_SOCK=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/tmp/localstack/data


volumes:
  localstack_data: